---
title: "Home"
site: workflowr::wflow_site
---

# Data Description

Multiplexed Ion Beam Imaging (spatial proteomics) dataset from 
"A Structured Tumor-Immune Microenvironment in Triple Negative 
Breast Cancer Revealed by Multiplexed Ion Beam Imaging" by Keren, L. et al.

DOI: https://dx.doi.org/10.1016/j.cell.2018.08.039

Journal: Cell 174, 1373-1387.e19 (2018).

# File Descriptions

## Exploratory Data Analysis

Exploratory and preliminary analysis of the data
including visualization about the abundance of different cell types, 
composition of the different samples, results for running MISTy on
all cells in each sample.

## Cell Type Specific Analysis

Running MISTy on certain cell type subsets only considering effects from
another subset for the calculation of the paraview.

## Model Comparison

Internal Benchmark of different ML algorithms to build view-specific models.

## Composition Analysis

Using MISTy to predict the identity of a cell using the neighboring cells.

## MISTy Helpgers

Showcase new MISTy helper functions to prepare the samples for running MISTy

## Question

Some questions that came up during the analysis and remain unresolved.

## Presentation

Contains (or will contain) some of the interesting results.
