---
title: "Presentation"
---

# Questions

1. How does the site/location in the solid tumor where the sample is taken from
influence the sample-to-sample heterogeneity?
- See discussion of the paper: Emerging cohorts, in which several regions are 
profiled for each patient, are needed to investigate the intra-patient 
heterogeneity in the composition and architecture of the tumor-immune 
microenvironment and its relationship to the molecular attributes of the tumor.

2. What are the different markers indicative of?
- Tumor-related: EGFR, p53, Keratin6, Keratin17, Pan-Keratin,
- Metabolic activity / proliferation: Ki-67, pS6
- Immunoregulatory proteins: PD-1, PD-L1, LAG3, IDO
- Macrophages: CD68, CD11b (or pan-myeloid marker)
- Dendritic Cells (DC): CD209, CD11c,
- General Marker for Leukocytes: CD45
- Neutrophils: MPO, 
- T-cells: CD4 (helper), CD8 (cytotoxic), 
- B-cells: CD20, 
- Epithelial cells: CD138

3. On which other MIBI datasets could we test MISTy on?
- Spatio-temporal coordination at the maternal-fetal interface promotes 
trophoblast invasion and vascular remodeling in the first half of human pregnancy

4. Do we even have enough markers to discover cell-cell interaction?
- As I understand it most markers were chosen to distinguish between different
cell types, but we get little information about the cell states (meaning, 
what is actually going on in those cells).

5. What factors could explain that we can sometimes explain more or less 
variance for certain target in certain samples? What drives the performance
of MISTy?

6. Is it fair to use the same distance threshold for calculating the 
juxta and paraview for all the samples, or should the specific threshold
depend on some properties of the sample? For example for the
juxtaview the median of the following stat: "mean distance to the neighboring 
cells for each cell i"

7. Why is the gain in explained variance so high for CD138, what is this
effect driven by?